### ISSUE TITLE
TypeError: name must be an instance of str

### ISSUE THREAD

**Issue by jbc222** [hitsz-ids/airda#18]
(airda) PS C:\Users\Administrator> airda datasource add -n mydatasource -h localhost -p 3306 -k MYSQL -d sakila
Traceback (most recent call last):
  File "D:\conda\envs\airda\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\conda\envs\airda\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\conda\envs\airda\Scripts\airda.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\conda\envs\airda\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\conda\envs\airda\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\conda\envs\airda\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\conda\envs\airda\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\conda\envs\airda\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\conda\envs\airda\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\conda\envs\airda\lib\site-packages\airda\cli\startup.py", line 177, in add
    context = DataAgent(DataAgentKey.STORAGE).run()
  File "D:\conda\envs\airda\lib\site-packages\airda\agent\agent.py", line 27, in __init__
    self.context.load_storage()
  File "D:\conda\envs\airda\lib\site-packages\airda\agent\data_agent_context.py", line 18, in load_storage
    super().load(DataAgentKey.STORAGE, DataAgentStorage)
  File "D:\conda\envs\airda\lib\site-packages\airda\framework\agent\context.py", line 46, in load
    self._load_by_type(key, module, False, context=self)
  File "D:\conda\envs\airda\lib\site-packages\airda\framework\agent\context.py", line 54, in _load_by_type
    self._create_module(key, module, **kwargs)
  File "D:\conda\envs\airda\lib\site-packages\airda\framework\agent\context.py", line 57, in _create_module
    module = cls(**kwargs)
  File "D:\conda\envs\airda\lib\site-packages\airda\agent\storage\storage.py", line 27, in __init__
    self.init_storage()
  File "D:\conda\envs\airda\lib\site-packages\airda\agent\storage\storage.py", line 41, in init_storage
    self.database = self.client[db_name]
  File "D:\conda\envs\airda\lib\site-packages\pymongo\synchronous\mongo_client.py", line 1183, in __getitem__
    return database.Database(self, name)
  File "D:\conda\envs\airda\lib\site-packages\pymongo\synchronous\database.py", line 125, in __init__
    raise TypeError("name must be an instance of str")
TypeError: name must be an instance of str

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version:
- Browser and version(if necessary):
- Which version are you using:

<details><summary>Error message</summary>
<pre>
Paste complete error message, logs, or stack traces here.
</pre>
</details>

<details><summary>Configuration</summary>
<pre>
Paste the contents of your configuration file here.
</pre>
</details>

<details><summary>Additional context</summary>
<pre>
</pre>
</details>

**Comment by jbc222** [comment]
运行了好几次，都不行

**Comment by SoiTeoh** [comment]
大佬，解决了没有，我也遇到了同样的问题
